/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  publicDocSidebar: [{ type: "autogenerated", dirName: "public-networks" }],
  privateDocSidebar: [{ type: "autogenerated", dirName: "private-networks" }],

  // The plugins sidebar is mostly autogenerated, but the "Reference > Plugin API"
  // entry is a direct link to the Javadoc served from static/plugin-api/ rather
  // than a Docusaurus-managed doc page.
  pluginsDocSidebar: [
    { type: "doc", id: "plugins/index" },
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      link: { type: "generated-index", slug: "/plugins/get-started" },
      items: [{ type: "autogenerated", dirName: "plugins/get-started" }],
    },
    {
      type: "category",
      label: "Plugin services",
      link: {
        type: "generated-index",
        slug: "/plugins/services",
        description:
          "Besu plugins use Plugin API services to observe Besu activity, expose new APIs, provide custom components, or integrate Besu with external systems. Choose the page that matches what your plugin needs to do:",
      },
      items: [{ type: "autogenerated", dirName: "plugins/services" }],
    },
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "/plugins/how-to" },
      items: [{ type: "autogenerated", dirName: "plugins/how-to" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "/plugins/reference" },
      items: [
        {
          type: "link",
          label: "Plugin API",
          href: "pathname:///plugins/reference/plugin-api/index.html",
          description: "Open the Plugin API Javadoc.",
        },
        { type: "doc", id: "plugins/reference/resources" },
      ],
    },
  ],
};

module.exports = sidebars;
